import React from 'react';
import {Jumbotron, Container, Button} from 'react-bootstrap'
import Collapsible from "../collapsible/collapsible"
import "./cs464.css"
import assignment1 from "./assignment1.JPG"

export default class CS464 extends React.Component {
    render(){
        return(
            <div id="cs464">
                <h1>CS464: Topics in Societal Impacts</h1>
                <br/>
                <p>Below, you will find my course assignments for CS464, taken during Spring of 2022. This class is centered around areas of impact of computer technology on aspects of society and ethics such as: freedom versus the rule of law in cyberspace; social discourse; privacy; livelihoods and automation; fairness; security; political change; business models; technology divide.</p>
                <div className='assignments-div'>
                <Collapsible 
                    header={"Assignment 1: Which Reality?"}
                    detail={
                    <div>
                        <p className='assignment-description'><b>Description: </b>After reading Our Reality by Tadayoshi Kohno, I created an interpretive drawing based on the novella.</p>
                        <div className='flex-row'>
                        <p style={{width:"50%"}}>As Liam puts on his borrowed Goggles, he enters the virtual world of Our Reality. In one eye, he sees an ethereal world full of bright lights and color: ads flashing before his eyes, trying to get his attention and click. In the other, he sees the drab and dingy hallway of his real-world school: with dismal facilities and rundown lockers. The disparity between the two is vast and hard to comprehend. But it is now time for him to decide: Which Reality? Which is <b>HIS</b> Reality? Which <b>IS</b> Reality?</p>
                        <img src={assignment1} id="assignment-img"/>
                        </div>
                    </div>}
                />
                <Collapsible 
                    header={"Assignment 2: Technology Journal"}
                    detail={<div>
                        <p className='assignment-description'><b>Description: </b>For 10 days, I journaled about my daily relationship with technology. Many of the journal entries relate to the book we were reading during class: Reclaiming Conversation: The Power of Talk in a Digital Age by Sherry Turkle.</p>
                        <Collapsible 
                            header={"Feb 2 - Wednesday"}
                            detail={<div className='flex-row'>
                                <p>The reading for today’s discussion really hit home. I always knew that phones deterred me from relating to other people and from engaging in meaningful conversations. I am ashamed to admit that there have been countless times where I was extremely tempted to look at my phone while my friends are conversing around me–and most of the time, the temptation won. In the reading, the author mentioned that a group of friends had a rule where when the group met up for meals, there had to be a specific number of them engaged in conversation before she would allow herself to look down at her phone. I wonder if I should ask my friends to implement a similar rule. I agree with that girl how this rule would end up with everyone saying “what” to reconnect with the conversation. I see myself and my friends doing the same thing during group conversations. But isn’t being in and out of a conversation better than not being in it at all? I wonder about this all the time. At least in my friend group, there are usually 2 to 3 conversations happening at the same time. All of our attention is divided between the private conversation we are currently having and listening to the other conversations around the table–just in case one became more interesting. This was the norm for my group. And when one conversation is more interesting than the other smaller, private conversations, then everyone stops and comes back together for full-group conversations. This is exhausting sometimes, because I constantly have to pay attention to the person I am talking to, but I also have to keep one ear open to see if I want to join any of the other conversations going on elsewhere.</p>
                                </div>}
                        />
                        <Collapsible 
                            header={"Feb 3 - Thursday"}
                            detail={<div className='flex-row'>
                                <p>I am excited because tomorrow (Friday), I get to go to a conference in Indiana with my campus fellowship. Even though we will have to drive at the tail end of the storm, I think it will be worth getting away from campus for a few days. Since the conference schedule is jam-packed with activities, and since I will have the opportunity to spend time with people I don’t usually get to, I want to be on my phone as little as possible. Going along with what I’m reading for this class, I want to be more cognizant of how I use my phones and whether I am simply using my phone to avoid uncomfortable conversations. I want to use this weekend to have more meaningful conversations with the people around me and to not get distracted by what might be on my phone. A couple of my friends came over after dinner to play Dutch Blitz and Catan. It was a group that frequently met (pretty much weekly) to play the same two games together. We loved it though. When we are playing, no one was on their phones. We were all totally engrossed in the game! Even when a certain player was taking an extra-long time to decide on their next move, I noticed that no one took the time to pull out their phone. They too, were thinking about their next moves. I love playing board games because I feel like it is quality time spent together with few to no distractions.</p>
                                </div>}
                        />
                        <Collapsible 
                            header={"Feb 4 - Friday"}
                            detail={<div className='flex-row'>
                                <p>We drove to Indianapolis this afternoon. Maybe it was the preference of the driver, or maybe it was because of the trailer truck graveyards we saw as we drove down the interstate (a lot of trucks swerved off the highway due to the snow and icy conditions), but no one brought up needing to put on music during the entire drive. While some parts of the drive were filled with silence, there were also meaningful conversations that occurred organically. With no music playing, no one was singing along, and thus the conversations weren’t interrupted by anything. I had a great time looking out the window and just taking in how beautiful the snowy landscape was. Although some people in the car used their phones occasionally to text others, no one was glued to their phones. Once we got to the conference, I didn’t even have time to check my phone! I had a great time playing card games with my friends. We also took a night walk around Indianapolis. When we came across a cool arch-like sculpture, I couldn't help myself but to ask the group to take a group picture in front of it. Since it was close to midnight, there was no one around to take the picture for us. This was where my Apple Watch came in handy. I can prop up my phone a few feet in front of us, have everyone pose and get ready, and then click a button on my watch to take the photo. It was extremely easy to use and super helpful in situations like this!!</p>
                                </div>}
                        />
                        <Collapsible 
                            header={"Feb 5 - Saturday"}
                            detail={<div className='flex-row'>
                                <p>Being at the conference the entire day, I only occasionally checked my phone and only used it to communicate with others. My day was filled with fun workshops, large-group talks, and walking around Indianapolis. When I am not distracted with my phone, I was able to notice more of the environment around me. With the storm that just passed, I noticed that a lot of smaller shops in the downtown area were closed, and posted signs calling it “snowmageddon”! I also had a blast playing wacky board games during our downtime in the afternoon. I also met a few students from Purdue and we all went to dinner together! It was such a fun time. After dinner, when we went back to our hotel room, we had a few minutes before needing to head to the next large-group session. I couldn’t help myself but post the pictures from last night to my Instagram story. The urge to share my “fun” and “interesting” life online was too great. I definitely was not paying attention to the conversation happening at the time. Instead, I was hyperfocused on matching the text to the image and coming up with a fun caption. It took me multiple tries to get the story just right before posting. This reminded me of how the author in the reading for this class talked about how we prefer telecommunication because it allows us to edit and revise our speech before committing to it (ie posting it). It allows us to control how we come across online. I totally agree with this sentiment. I see myself stumbling over my words sometimes during real-time conversations today. But when it came to posting on Instagram, I had all the time I needed to come up with the best possible caption that will captivate my “audience”.</p>
                                </div>}
                        />
                        <Collapsible 
                            header={"Feb 6 - Sunday"}
                            detail={<div className='flex-row'>
                                <p>Today we went home in the afternoon. I must admit that I am all peopled-out. I would consider myself an extroverted introvert. And spending the whole weekend constantly surrounded by people really drained me. I was so ready to go back to sleeping in my own bed and spending alone me-time. On the ride back, I noticed myself needing to catch up with all of the notifications on my phone that I had missed in the past few days. And boy was there a lot! It took me a while to get through it all. Then when I got home, I immediately took a nap. But the moment I woke up, started playing Netflix in the background. No matter what it was that I was doing–whether it was cooking, eating, cleaning, or taking a shower, I had a Netflix show playing in the background. I have grown accustomed to always having some sort of background noise in my life–most of the time it is a show that I have already watched over 3 or 4 times. It was comforting for me to rewatch shows. Because I don’t have to focus 100% of my attention on it. I already know the catch lines and the most important moments. I can practically quote entire scenes from these shows because of how many times I have rewatched them! But still, I can’t bear to live in silence. Like the author mentioned in the reading for this class, we are scared of solitude and constantly avoid it. I think I was avoiding solitude and being alone with my thoughts by constantly semi-distracting myself and trying to multitask. I was obviously not focused on the show, but nor was I solely focused on the task at hand. I have become so accustomed to this routine that if I don’t have a show playing in the background, I don’t know what to do with myself. Maybe it is time for a change.</p>
                                </div>}
                        />
                        <Collapsible 
                            header={"Feb 7 - Monday"}
                            detail={<div className='flex-row'>
                                <p>After reading the last chapters in Reclaiming Conversation today, I feel a new vigor to combat my addiction to my phone and to start spending time in true solitude. I want to take note of how I am using my phone and other devices and decide to what end I am using them for.  I want to make a change in my life to find myself in solitude. The author says that without solitude, you cannot find yourself nor the confidence in yourself to face other people. I agree with this, which is why I must make a change. I want to spend more time just journaling my thoughts and reflecting on the day. I want to take more of a mental note of what is happening around me and what has happened throughout the day. Instead of living from task to task, constantly thinking and worrying about the next task to do, I should focus on the task at hand. Today, I worked on my MP without having a show playing in the background. At first, I hated the silence. But soon, I was so engrossed in the code that I didn’t it notice that a couple of hours had passed! It was so weird because I usually dread spending hours at my desk without taking a break. But I found that as I focused on the MP, I was able to be more productive and write code that had fewer errors.</p>
                                </div>}
                        />
                        <Collapsible 
                            header={"Feb 8 - Tuesday"}
                            detail={<div className='flex-row'>
                                <p>Today was a busy day, where my schedule was packed with classes and work. At night, the office had an all-hands meeting. It was nice to see everyone together in the office, since the last time we all saw each other was before winter break. It’s easy to see that there were cliques in the office. The girls–the small percentage of us–usually stuck together because the rest of the engineering interns were all guys. But today, there were a couple of new interns in the room who had just started working for us this week. I was excited to meet them and to talk to them. But obviously, it was quite awkward at first. I was tempted to not go out of my personal bubble and to just sit in a conversation that I had no interest in, or to scroll through my phone. Oh, the urge to pull out my phone and randomly scroll through Instagram was so strong! It was so much easier than conversing with co-workers that I barely know. Even though most of us are all interns and all in engineering, it was still hard to find common interests to talk about. It was easy to exchange pleasantries, but that’s as far as most people go. I decided to put my newfound determination of not being glued to my phone to the test. I introduced myself to the new interns and struck up a conversation. It was nice! I am proud of myself to have not have been solely on my phone during the entire event.</p>
                                </div>}
                        />
                        <Collapsible 
                            header={"Feb 10 - Thursday"}
                            detail={<div className='flex-row'>
                                <p>I was shocked by the reading for this class, Weapons of Math Destruction. Especially the chapter on the US News college rankings. When I was applying to schools during my senior year of high school, the ranking definitely affected where I applied to. I mostly only applied to private schools and the schools in the top 7 in the rankings for Computer Science. And tada, here I am in the middle of a cornfield simply because UIUC is so highly ranked for computer science! I had never really thought much about how the rankings were made and what were the reasons and criteria behind them. One thing that really stuck out to me from the chapter–that I really pondered on–was how the schools are graded on a curve every year. That means if a college has a lower rank and wants to increase its rank, it can focus on fundraising. They can have the best fundraising year, and get away bigger budget than in previous years. But this might not boost them in the ratings if other schools in the area were able to fundraise a lot more than them in that particular year. This means that even if a college does better when compared to themselves in previous years, they still have to outperform other schools in order to boost their ranking. One of the reasons why I didn’t apply to any University of California schools (I am originally from California) was precisely because they tend to grade students on a curve. This means that only a specific percentage of students got As, Bs, Cs, and so on. This creates an extremely competitive environment, where students don’t care about how much they are learning or how much they are improving from who they were a year ago; but solely care about how they fare against their friends and classmates. To think that the only reason I even applied to UIUC was because of a ranking system that was based on a curve when I didn’t apply to any UCs because of that exact reason shocked me. From now on, I need to do more research before putting my trust in a system and model that I don’t 100% believe in.</p>
                                </div>}
                        />
                        <Collapsible 
                            header={"Feb 12 - Saturday"}
                            detail={<div className='flex-row'>
                                <p>Today, my friends and I celebrated Galentine’s Day. The rest of my friends all live in the same house, whereas I live in an apartment a block away. It is extremely easy for them to communicate in person and to have organic, natural interactions whenever they bump into each other. But as for me, I tend to miss out on some small communication details simply because I don’t see them unless planned beforehand. They were supposed to come to my apartment to celebrate Galentine’s Day after dinner. We were going to just hang out, eat some snacks, and chill. No one notified me that one of our friend’s boyfriends drove all the way here for Virginia to surprise her. And because of that, she was no longer available at night to be with us. It wasn’t until an hour before the agreed-upon time that I got a call saying she might not come. Then, over FaceTime, we continued to talk about whether to cancel the night or to just hang out without her. In my mind, I thought the night was canceled, but apparently, the rest of them on the other end of the phone thought the opposite. So I was extremely surprised when the rest of them showed up at my door later on. Don’t get me wrong, I was happy that we were able to hang out and spend time together. But I was a bit frustrated at how poorly we communicated. We have instant communication via text or a FaceTime call. But even when we have these channels of communication, there are still miscommunications and misunderstandings. This frustration helped me remember what the author of Reclaiming Conversation said about how even though we feel like we are more connected than ever before, but in actuality, are more disconnected and more lonely.</p>
                                </div>}
                        />
                        <Collapsible 
                            header={"Feb 15- Tuesday"}
                            detail={<div className='flex-row'>
                                <p>The reading for Wednesday was confounding. The chapter that stuck out to me the most was chapter 6, about how the interview process is automated and how automated models were created in order to generalize candidates into broad categories. I remember doing similar tests when applying for internships last year. At the start of the interview season, I wasl extremely nervous whenever I had to take a personality test or do an automated behavioral interview. But as I gained more experience, I realized that the algorithm didn’t care about who I was, but who I was portraying. Thus, even before I had the time to realize it, I began to enter these interviews, not as who I was, but who I wanted to be. If I sense that the company greatly valued diversity, I would play up how I immigrated from China as a child and how my unique perspective as an Asian American women in the tech industry has shaped me into who I am today. If I sense that the company greatly valued grit and perseverance, I would play up projects that tested my endurance. By the end of the interview season, every behavior interview and personality test have become more of a mind game–one where I tried to find what qualities the algorithm valued the most and played into it. It became less about authenticity and more about beating the system. I don’t think I was wrong in doing this. I didn’t lie in any of those tests or interviews. I simply downplayed certain aspects of myself while focusing on aspects of me that the company wanted to see. I don’t like how this was the only way for candidates to pass the interviews and for them to get a good internship and job offer. I wish that that system focused more on authenticity and vulnerability rather than finding a candidate with a list of qualities that were predetermined as “good”.</p>
                                </div>}
                        />
                        </div>}
                />
                <Collapsible 
                    header={"Assignment 3: Ross Ulbricht: martyr or mastermind?"}
                    detail={<div>
                        <p className='assignment-description'><b>Description: </b>The following is a blog-style entry regarding Ross Ulbricht, the creator of the Silk Road.</p>
                        <p>Undoubtedly, the creator of the “world’s first online drug bazaar” [1] must have intelligence. But intelligence without ambition is a bird without wings. Ross Ulbricht was an ambitious man who utilized up-and-coming technologies in his own design. Was he driven by the selfish need to leave a mark on the world–a legacy of some kind; or was he driven by something loftier–a political ideal not yet adopted by society? Either way, his life is immortalized in the book “American Kingpin: The Epic Hunt for the Criminal Mastermind Behind the Silk Road” by Nick Bolton.</p>
                        <p>Although Ross himself refused to comment on the book or its contents, Nick Bolton takes creative liberties in dramatizing the life of Ross Ulbricht. During his early twenties, Ross discovered Libertarianism, a set of political ideologies that revolves around less government control in civilian lives. Ross believes that the markets should decide societal problems, not the government, that “people [should] determine who should win; not the politicians” [2]. These ideals led Ross to create the Silk Road, the “Internet's largest and most sophisticated underground illicit goods market” [3] on the Dark Web. He through that through the Silk Road, he was “changing the world and making it a better place” [2], a place where drugs are accepted legalized.</p>
                        <p>The underlying technology behind the Silk Road was Bitcoin” an anonymous, digital, alternative currency that was outside of the control of any government. The emergence of the Silk Road had a direct relationship with the popularity of Bitcoin. For many, the “Silk Road has become a touchstone for Bitcoin’s utility and its role as a foil to the mainstream economic system” [4]. It was the first real use case for alternative currencies. When the Silk Road was finally taken down, there were 11.7 million bitcoins in circulation. Out of that amount, “the Silk Road handled BTC 9.5 million in transactions over its two-year life” [5]! Saying that the Silk Road was profitable was an understatement. It is estimated that “the website had generated commissions totaling more than 600,000 bitcoins” [6], all of which directly went into Ross’s personal wallet.</p>
                        <p>So the big question is: did Ross stay true to his beliefs or did the lust for money and fame overtake him? I argue that as the Silk Road grew, Ross’s stronghold on Libertarian ideals slipped more and more. At the end of the Silk Road journey, Ross was more enamored with leaving a glorious legacy and a fat wallet than he was of revolutionizing the drug trade. If he had stayed true to the cause, he would not have meticulously planned the perfect escape: one where his money and physical safety are ensured. Instead, he should have revealed his identity to become the true face of the movement. He should not have hid behind his computer and keyboard in the dark, but instead, have rallied his fellows in broad daylight. Another issue I find with Ross’s character was how he never shared his earning calls nor Silk Road source code with the world. If he had created the Silk Road as an open-source platform, it would have better matched his Libertarian ideologies. But he didn’t. Because he knew that if he did, the number of copycat sites would be endless and his profit margins would dwindle to nothing.</p>
                        <p>After reading American Kingpin, I agree with the sentencing judge in his case: “What is clear is that people are very, very complex and [Ross is] one of them. There is good in [Ross], but there is also bad, and what [he] did in connection with Silk Road was terribly destructive to our social fabric” [2].</p>
                        <p><a target="_blank" href='https://news.law.fordham.edu/jcfl/2018/02/21/silk-road-the-dark-side-of-cryptocurrency/'>[1] Silk Road: The Dark Side of Cryptocurrency</a></p>
                        <p><a target="_blank" href='https://www.amazon.com/dp/B08SQMNDQY/ref=apubna_br_gs_29892_tx_1_br_2203'>[2] American Kingpin: The Epic Hunt for the Criminal Mastermind Behind the Silk Road (by Nick Bilton)</a></p>
                        <p><a target="_blank" href='https://www.npr.org/sections/alltechconsidered/2013/10/03/228845525/all-about-dread-pirate-roberts-a-k-a-ross-ulbricht-bio-profile'>[3] What We Know About Ross Ulbricht, Or 'Dread Pirate Roberts'</a></p>
                        <p><a target="_blank" href='https://bitcoinmagazine.com/culture/the-long-and-winding-story-of-silk-road-bitcoins-earliest-major-application#:~:text=For%20many%20in%20the%20Bitcoin,three%20years%20after%20it%20launched.'>[4] The Long and Winding Story of Silk Road, Bitcoin's Earliest Major Application</a></p>
                        <p><a target="_blank" href='https://www.wired.com/2013/10/bitcoin-market-drops-600-million-on-silk-road-bust/'>[5] Bitcoin Values Plummet $500M, Then Recover, After Silk Road Bust</a></p>
                        <p><a target="_blank" href='https://www.wsj.com/articles/justice-department-seizes-1-billion-of-bitcoin-tied-to-silk-road-website-11604612072'>[6] Justice Department Seizes $1 Billion of Bitcoin Tied to Silk Road Website</a></p>
                        </div>}
                />
                <Collapsible 
                    header={"Assignment 4: Personal Action Plan Against a Dystopic Future"}
                    detail={<div>
                        <p><b>Ways of noticing dystopian possibilities</b></p>
                            <p>1. I will keep up to date with major developments in the field of tech: including new breakthrough technologies, legislative policies that impact tech, etc.</p>
                            <p>2. I will remember to educate myself on all of the different sides of a specific issue before making my own conclusion</p>
                        <p><b>Applications to personal life</b></p>
                            <p>1. I will educate friends and family who are not in tech of the potential benefits and harms of tech</p>
                        <p><b>Applications to work/professional life</b></p>
                            <p>1. I will not be bound to the golden handcuffs of working for a large tech company. Instead, I will be vigilant against predatory practices both within and outside of the company and be cautious of any environmental and societal impacts made by the tech</p>
                            <p>2. I will openly share my salaries and wages in order to promote transparency in hiring practices and compensation</p>
                        <p><b>Applications to broader societal impacts</b></p>
                            <p>1. I will take note of any technologies that increase the rate of climate change and make pointed efforts to confront such behavior</p>
                            <p>2. I will continue to make green choices in order to support environmental efforts</p>
                    </div>}
                />
                </div>
            </div>
        );
    }
}